/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.live.sb.demo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Course service. Represents a row in the &quot;SBDemo_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.live.sb.demo.model.impl.CourseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.live.sb.demo.model.impl.CourseImpl}.
 * </p>
 *
 * @author dnebinger
 * @see Course
 * @see com.liferay.live.sb.demo.model.impl.CourseImpl
 * @see com.liferay.live.sb.demo.model.impl.CourseModelImpl
 * @generated
 */
public interface CourseModel extends BaseModel<Course> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course model instance should use the {@link Course} interface instead.
	 */

	/**
	 * Returns the primary key of this course.
	 *
	 * @return the primary key of this course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course.
	 *
	 * @param primaryKey the primary key of this course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the course ID of this course.
	 *
	 * @return the course ID of this course
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course.
	 *
	 * @param courseId the course ID of this course
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the user ID of this course.
	 *
	 * @return the user ID of this course
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this course.
	 *
	 * @param userId the user ID of this course
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course.
	 *
	 * @return the user uuid of this course
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this course.
	 *
	 * @param userUuid the user uuid of this course
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this course.
	 *
	 * @return the create date of this course
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this course.
	 *
	 * @param createDate the create date of this course
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course.
	 *
	 * @return the modified date of this course
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course.
	 *
	 * @param modifiedDate the modified date of this course
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the instructor ID of this course.
	 *
	 * @return the instructor ID of this course
	 */
	public long getInstructorId();

	/**
	 * Sets the instructor ID of this course.
	 *
	 * @param instructorId the instructor ID of this course
	 */
	public void setInstructorId(long instructorId);

	/**
	 * Returns the course catalog ID of this course.
	 *
	 * @return the course catalog ID of this course
	 */
	public long getCourseCatalogId();

	/**
	 * Sets the course catalog ID of this course.
	 *
	 * @param courseCatalogId the course catalog ID of this course
	 */
	public void setCourseCatalogId(long courseCatalogId);

	/**
	 * Returns the credit hours of this course.
	 *
	 * @return the credit hours of this course
	 */
	public int getCreditHours();

	/**
	 * Sets the credit hours of this course.
	 *
	 * @param creditHours the credit hours of this course
	 */
	public void setCreditHours(int creditHours);

	/**
	 * Returns the semester of this course.
	 *
	 * @return the semester of this course
	 */
	public int getSemester();

	/**
	 * Sets the semester of this course.
	 *
	 * @param semester the semester of this course
	 */
	public void setSemester(int semester);

	/**
	 * Returns the year of this course.
	 *
	 * @return the year of this course
	 */
	public int getYear();

	/**
	 * Sets the year of this course.
	 *
	 * @param year the year of this course
	 */
	public void setYear(int year);

	/**
	 * Returns the name of this course.
	 *
	 * @return the name of this course
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this course.
	 *
	 * @param name the name of this course
	 */
	public void setName(String name);

	/**
	 * Returns the major of this course.
	 *
	 * @return the major of this course
	 */
	@AutoEscape
	public String getMajor();

	/**
	 * Sets the major of this course.
	 *
	 * @param major the major of this course
	 */
	public void setMajor(String major);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Course course);

	public int hashCode();

	public CacheModel<Course> toCacheModel();

	public Course toEscapedModel();

	public String toString();

	public String toXmlString();
}