/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.live.sb.demo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CourseCatalog service. Represents a row in the &quot;COURSE_CATALOG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.live.sb.demo.model.impl.CourseCatalogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.live.sb.demo.model.impl.CourseCatalogImpl}.
 * </p>
 *
 * @author dnebinger
 * @see CourseCatalog
 * @see com.liferay.live.sb.demo.model.impl.CourseCatalogImpl
 * @see com.liferay.live.sb.demo.model.impl.CourseCatalogModelImpl
 * @generated
 */
public interface CourseCatalogModel extends BaseModel<CourseCatalog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course catalog model instance should use the {@link CourseCatalog} interface instead.
	 */

	/**
	 * Returns the primary key of this course catalog.
	 *
	 * @return the primary key of this course catalog
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course catalog.
	 *
	 * @param primaryKey the primary key of this course catalog
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the course catalog ID of this course catalog.
	 *
	 * @return the course catalog ID of this course catalog
	 */
	public long getCourseCatalogId();

	/**
	 * Sets the course catalog ID of this course catalog.
	 *
	 * @param courseCatalogId the course catalog ID of this course catalog
	 */
	public void setCourseCatalogId(long courseCatalogId);

	/**
	 * Returns the user ID of this course catalog.
	 *
	 * @return the user ID of this course catalog
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this course catalog.
	 *
	 * @param userId the user ID of this course catalog
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course catalog.
	 *
	 * @return the user uuid of this course catalog
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this course catalog.
	 *
	 * @param userUuid the user uuid of this course catalog
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this course catalog.
	 *
	 * @return the create date of this course catalog
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this course catalog.
	 *
	 * @param createDate the create date of this course catalog
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course catalog.
	 *
	 * @return the modified date of this course catalog
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course catalog.
	 *
	 * @param modifiedDate the modified date of this course catalog
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this course catalog.
	 *
	 * @return the name of this course catalog
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this course catalog.
	 *
	 * @param name the name of this course catalog
	 */
	public void setName(String name);

	/**
	 * Returns the description of this course catalog.
	 *
	 * @return the description of this course catalog
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this course catalog.
	 *
	 * @param description the description of this course catalog
	 */
	public void setDescription(String description);

	/**
	 * Returns the major of this course catalog.
	 *
	 * @return the major of this course catalog
	 */
	@AutoEscape
	public String getMajor();

	/**
	 * Sets the major of this course catalog.
	 *
	 * @param major the major of this course catalog
	 */
	public void setMajor(String major);

	/**
	 * Returns the credit hours of this course catalog.
	 *
	 * @return the credit hours of this course catalog
	 */
	public int getCreditHours();

	/**
	 * Sets the credit hours of this course catalog.
	 *
	 * @param creditHours the credit hours of this course catalog
	 */
	public void setCreditHours(int creditHours);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CourseCatalog courseCatalog);

	public int hashCode();

	public CacheModel<CourseCatalog> toCacheModel();

	public CourseCatalog toEscapedModel();

	public String toString();

	public String toXmlString();
}