/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.live.sb.demo.model;

import com.liferay.live.sb.demo.service.persistence.CourseStudentPK;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CourseStudent service. Represents a row in the &quot;SBDemo_CourseStudent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.live.sb.demo.model.impl.CourseStudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.live.sb.demo.model.impl.CourseStudentImpl}.
 * </p>
 *
 * @author dnebinger
 * @see CourseStudent
 * @see com.liferay.live.sb.demo.model.impl.CourseStudentImpl
 * @see com.liferay.live.sb.demo.model.impl.CourseStudentModelImpl
 * @generated
 */
public interface CourseStudentModel extends BaseModel<CourseStudent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course student model instance should use the {@link CourseStudent} interface instead.
	 */

	/**
	 * Returns the primary key of this course student.
	 *
	 * @return the primary key of this course student
	 */
	public CourseStudentPK getPrimaryKey();

	/**
	 * Sets the primary key of this course student.
	 *
	 * @param primaryKey the primary key of this course student
	 */
	public void setPrimaryKey(CourseStudentPK primaryKey);

	/**
	 * Returns the student ID of this course student.
	 *
	 * @return the student ID of this course student
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this course student.
	 *
	 * @param studentId the student ID of this course student
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the course ID of this course student.
	 *
	 * @return the course ID of this course student
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course student.
	 *
	 * @param courseId the course ID of this course student
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the user ID of this course student.
	 *
	 * @return the user ID of this course student
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this course student.
	 *
	 * @param userId the user ID of this course student
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course student.
	 *
	 * @return the user uuid of this course student
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this course student.
	 *
	 * @param userUuid the user uuid of this course student
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this course student.
	 *
	 * @return the create date of this course student
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this course student.
	 *
	 * @param createDate the create date of this course student
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course student.
	 *
	 * @return the modified date of this course student
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course student.
	 *
	 * @param modifiedDate the modified date of this course student
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the grade of this course student.
	 *
	 * @return the grade of this course student
	 */
	public double getGrade();

	/**
	 * Sets the grade of this course student.
	 *
	 * @param grade the grade of this course student
	 */
	public void setGrade(double grade);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CourseStudent courseStudent);

	public int hashCode();

	public CacheModel<CourseStudent> toCacheModel();

	public CourseStudent toEscapedModel();

	public String toString();

	public String toXmlString();
}