/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.live.sb.demo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the StudentGPA service. Represents a row in the &quot;SBDemo_StudentGPA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.live.sb.demo.model.impl.StudentGPAModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.live.sb.demo.model.impl.StudentGPAImpl}.
 * </p>
 *
 * @author dnebinger
 * @see StudentGPA
 * @see com.liferay.live.sb.demo.model.impl.StudentGPAImpl
 * @see com.liferay.live.sb.demo.model.impl.StudentGPAModelImpl
 * @generated
 */
public interface StudentGPAModel extends BaseModel<StudentGPA> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student g p a model instance should use the {@link StudentGPA} interface instead.
	 */

	/**
	 * Returns the primary key of this student g p a.
	 *
	 * @return the primary key of this student g p a
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student g p a.
	 *
	 * @param primaryKey the primary key of this student g p a
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this student g p a.
	 *
	 * @return the student ID of this student g p a
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student g p a.
	 *
	 * @param studentId the student ID of this student g p a
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the name of this student g p a.
	 *
	 * @return the name of this student g p a
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this student g p a.
	 *
	 * @param name the name of this student g p a
	 */
	public void setName(String name);

	/**
	 * Returns the grade points of this student g p a.
	 *
	 * @return the grade points of this student g p a
	 */
	public double getGradePoints();

	/**
	 * Sets the grade points of this student g p a.
	 *
	 * @param gradePoints the grade points of this student g p a
	 */
	public void setGradePoints(double gradePoints);

	/**
	 * Returns the year of this student g p a.
	 *
	 * @return the year of this student g p a
	 */
	public int getYear();

	/**
	 * Sets the year of this student g p a.
	 *
	 * @param year the year of this student g p a
	 */
	public void setYear(int year);

	/**
	 * Returns the semester of this student g p a.
	 *
	 * @return the semester of this student g p a
	 */
	public int getSemester();

	/**
	 * Sets the semester of this student g p a.
	 *
	 * @param semester the semester of this student g p a
	 */
	public void setSemester(int semester);

	/**
	 * Returns the credit hours of this student g p a.
	 *
	 * @return the credit hours of this student g p a
	 */
	public int getCreditHours();

	/**
	 * Sets the credit hours of this student g p a.
	 *
	 * @param creditHours the credit hours of this student g p a
	 */
	public void setCreditHours(int creditHours);

	/**
	 * Returns the gpa of this student g p a.
	 *
	 * @return the gpa of this student g p a
	 */
	public double getGpa();

	/**
	 * Sets the gpa of this student g p a.
	 *
	 * @param gpa the gpa of this student g p a
	 */
	public void setGpa(double gpa);

	/**
	 * Returns the letter grade of this student g p a.
	 *
	 * @return the letter grade of this student g p a
	 */
	@AutoEscape
	public String getLetterGrade();

	/**
	 * Sets the letter grade of this student g p a.
	 *
	 * @param letterGrade the letter grade of this student g p a
	 */
	public void setLetterGrade(String letterGrade);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(StudentGPA studentGPA);

	public int hashCode();

	public CacheModel<StudentGPA> toCacheModel();

	public StudentGPA toEscapedModel();

	public String toString();

	public String toXmlString();
}