/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.live.sb.demo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Student service. Represents a row in the &quot;SBDemo_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.live.sb.demo.model.impl.StudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.live.sb.demo.model.impl.StudentImpl}.
 * </p>
 *
 * @author dnebinger
 * @see Student
 * @see com.liferay.live.sb.demo.model.impl.StudentImpl
 * @see com.liferay.live.sb.demo.model.impl.StudentModelImpl
 * @generated
 */
public interface StudentModel extends BaseModel<Student> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link Student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this student.
	 *
	 * @return the student ID of this student
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student.
	 *
	 * @param studentId the student ID of this student
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the user ID of this student.
	 *
	 * @return the user ID of this student
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this student.
	 *
	 * @param userId the user ID of this student
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this student.
	 *
	 * @return the user uuid of this student
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this student.
	 *
	 * @param userUuid the user uuid of this student
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this student.
	 *
	 * @return the create date of this student
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this student.
	 *
	 * @param createDate the create date of this student
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this student.
	 *
	 * @return the modified date of this student
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this student.
	 *
	 * @param modifiedDate the modified date of this student
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this student.
	 *
	 * @return the name of this student
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this student.
	 *
	 * @param name the name of this student
	 */
	public void setName(String name);

	/**
	 * Returns the enrolled of this student.
	 *
	 * @return the enrolled of this student
	 */
	public boolean getEnrolled();

	/**
	 * Returns <code>true</code> if this student is enrolled.
	 *
	 * @return <code>true</code> if this student is enrolled; <code>false</code> otherwise
	 */
	public boolean isEnrolled();

	/**
	 * Sets whether this student is enrolled.
	 *
	 * @param enrolled the enrolled of this student
	 */
	public void setEnrolled(boolean enrolled);

	/**
	 * Returns the enrollment date of this student.
	 *
	 * @return the enrollment date of this student
	 */
	public Date getEnrollmentDate();

	/**
	 * Sets the enrollment date of this student.
	 *
	 * @param enrollmentDate the enrollment date of this student
	 */
	public void setEnrollmentDate(Date enrollmentDate);

	/**
	 * Returns the year in school of this student.
	 *
	 * @return the year in school of this student
	 */
	public int getYearInSchool();

	/**
	 * Sets the year in school of this student.
	 *
	 * @param yearInSchool the year in school of this student
	 */
	public void setYearInSchool(int yearInSchool);

	/**
	 * Returns the major of this student.
	 *
	 * @return the major of this student
	 */
	@AutoEscape
	public String getMajor();

	/**
	 * Sets the major of this student.
	 *
	 * @param major the major of this student
	 */
	public void setMajor(String major);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Student student);

	public int hashCode();

	public CacheModel<Student> toCacheModel();

	public Student toEscapedModel();

	public String toString();

	public String toXmlString();
}