/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.live.sb.demo.model.impl;

import com.liferay.live.sb.demo.model.Course;
import com.liferay.live.sb.demo.model.CourseModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Course service. Represents a row in the &quot;SBDemo_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.live.sb.demo.model.CourseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseImpl}.
 * </p>
 *
 * @author dnebinger
 * @see CourseImpl
 * @see com.liferay.live.sb.demo.model.Course
 * @see com.liferay.live.sb.demo.model.CourseModel
 * @generated
 */
public class CourseModelImpl extends BaseModelImpl<Course>
	implements CourseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course model instance should use the {@link com.liferay.live.sb.demo.model.Course} interface instead.
	 */
	public static final String TABLE_NAME = "SBDemo_Course";
	public static final Object[][] TABLE_COLUMNS = {
			{ "courseId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "instructorId", Types.BIGINT },
			{ "courseCatalogId", Types.BIGINT },
			{ "creditHours", Types.INTEGER },
			{ "semester", Types.INTEGER },
			{ "year", Types.INTEGER },
			{ "name", Types.VARCHAR },
			{ "major", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SBDemo_Course (courseId LONG not null primary key,userId LONG,createDate DATE null,modifiedDate DATE null,instructorId LONG,courseCatalogId LONG,creditHours INTEGER,semester INTEGER,year INTEGER,name VARCHAR(75) null,major VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SBDemo_Course";
	public static final String ORDER_BY_JPQL = " ORDER BY course.year ASC, course.semester ASC, course.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SBDemo_Course.year ASC, SBDemo_Course.semester ASC, SBDemo_Course.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.live.sb.demo.model.Course"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.live.sb.demo.model.Course"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.live.sb.demo.model.Course"),
			true);
	public static long COURSECATALOGID_COLUMN_BITMASK = 1L;
	public static long INSTRUCTORID_COLUMN_BITMASK = 2L;
	public static long SEMESTER_COLUMN_BITMASK = 4L;
	public static long YEAR_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.live.sb.demo.model.Course"));

	public CourseModelImpl() {
	}

	public long getPrimaryKey() {
		return _courseId;
	}

	public void setPrimaryKey(long primaryKey) {
		setCourseId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_courseId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Course.class;
	}

	public String getModelClassName() {
		return Course.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("courseId", getCourseId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("instructorId", getInstructorId());
		attributes.put("courseCatalogId", getCourseCatalogId());
		attributes.put("creditHours", getCreditHours());
		attributes.put("semester", getSemester());
		attributes.put("year", getYear());
		attributes.put("name", getName());
		attributes.put("major", getMajor());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long courseId = (Long)attributes.get("courseId");

		if (courseId != null) {
			setCourseId(courseId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long instructorId = (Long)attributes.get("instructorId");

		if (instructorId != null) {
			setInstructorId(instructorId);
		}

		Long courseCatalogId = (Long)attributes.get("courseCatalogId");

		if (courseCatalogId != null) {
			setCourseCatalogId(courseCatalogId);
		}

		Integer creditHours = (Integer)attributes.get("creditHours");

		if (creditHours != null) {
			setCreditHours(creditHours);
		}

		Integer semester = (Integer)attributes.get("semester");

		if (semester != null) {
			setSemester(semester);
		}

		Integer year = (Integer)attributes.get("year");

		if (year != null) {
			setYear(year);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String major = (String)attributes.get("major");

		if (major != null) {
			setMajor(major);
		}
	}

	public long getCourseId() {
		return _courseId;
	}

	public void setCourseId(long courseId) {
		_courseId = courseId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getInstructorId() {
		return _instructorId;
	}

	public void setInstructorId(long instructorId) {
		_columnBitmask |= INSTRUCTORID_COLUMN_BITMASK;

		if (!_setOriginalInstructorId) {
			_setOriginalInstructorId = true;

			_originalInstructorId = _instructorId;
		}

		_instructorId = instructorId;
	}

	public long getOriginalInstructorId() {
		return _originalInstructorId;
	}

	public long getCourseCatalogId() {
		return _courseCatalogId;
	}

	public void setCourseCatalogId(long courseCatalogId) {
		_columnBitmask |= COURSECATALOGID_COLUMN_BITMASK;

		if (!_setOriginalCourseCatalogId) {
			_setOriginalCourseCatalogId = true;

			_originalCourseCatalogId = _courseCatalogId;
		}

		_courseCatalogId = courseCatalogId;
	}

	public long getOriginalCourseCatalogId() {
		return _originalCourseCatalogId;
	}

	public int getCreditHours() {
		return _creditHours;
	}

	public void setCreditHours(int creditHours) {
		_creditHours = creditHours;
	}

	public int getSemester() {
		return _semester;
	}

	public void setSemester(int semester) {
		_columnBitmask = -1L;

		if (!_setOriginalSemester) {
			_setOriginalSemester = true;

			_originalSemester = _semester;
		}

		_semester = semester;
	}

	public int getOriginalSemester() {
		return _originalSemester;
	}

	public int getYear() {
		return _year;
	}

	public void setYear(int year) {
		_columnBitmask = -1L;

		if (!_setOriginalYear) {
			_setOriginalYear = true;

			_originalYear = _year;
		}

		_year = year;
	}

	public int getOriginalYear() {
		return _originalYear;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	public String getMajor() {
		if (_major == null) {
			return StringPool.BLANK;
		}
		else {
			return _major;
		}
	}

	public void setMajor(String major) {
		_major = major;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Course.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Course toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Course)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		CourseImpl courseImpl = new CourseImpl();

		courseImpl.setCourseId(getCourseId());
		courseImpl.setUserId(getUserId());
		courseImpl.setCreateDate(getCreateDate());
		courseImpl.setModifiedDate(getModifiedDate());
		courseImpl.setInstructorId(getInstructorId());
		courseImpl.setCourseCatalogId(getCourseCatalogId());
		courseImpl.setCreditHours(getCreditHours());
		courseImpl.setSemester(getSemester());
		courseImpl.setYear(getYear());
		courseImpl.setName(getName());
		courseImpl.setMajor(getMajor());

		courseImpl.resetOriginalValues();

		return courseImpl;
	}

	public int compareTo(Course course) {
		int value = 0;

		if (getYear() < course.getYear()) {
			value = -1;
		}
		else if (getYear() > course.getYear()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getSemester() < course.getSemester()) {
			value = -1;
		}
		else if (getSemester() > course.getSemester()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getName().compareTo(course.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Course course = null;

		try {
			course = (Course)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = course.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CourseModelImpl courseModelImpl = this;

		courseModelImpl._originalInstructorId = courseModelImpl._instructorId;

		courseModelImpl._setOriginalInstructorId = false;

		courseModelImpl._originalCourseCatalogId = courseModelImpl._courseCatalogId;

		courseModelImpl._setOriginalCourseCatalogId = false;

		courseModelImpl._originalSemester = courseModelImpl._semester;

		courseModelImpl._setOriginalSemester = false;

		courseModelImpl._originalYear = courseModelImpl._year;

		courseModelImpl._setOriginalYear = false;

		courseModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Course> toCacheModel() {
		CourseCacheModel courseCacheModel = new CourseCacheModel();

		courseCacheModel.courseId = getCourseId();

		courseCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			courseCacheModel.createDate = createDate.getTime();
		}
		else {
			courseCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			courseCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			courseCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		courseCacheModel.instructorId = getInstructorId();

		courseCacheModel.courseCatalogId = getCourseCatalogId();

		courseCacheModel.creditHours = getCreditHours();

		courseCacheModel.semester = getSemester();

		courseCacheModel.year = getYear();

		courseCacheModel.name = getName();

		String name = courseCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			courseCacheModel.name = null;
		}

		courseCacheModel.major = getMajor();

		String major = courseCacheModel.major;

		if ((major != null) && (major.length() == 0)) {
			courseCacheModel.major = null;
		}

		return courseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{courseId=");
		sb.append(getCourseId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", instructorId=");
		sb.append(getInstructorId());
		sb.append(", courseCatalogId=");
		sb.append(getCourseCatalogId());
		sb.append(", creditHours=");
		sb.append(getCreditHours());
		sb.append(", semester=");
		sb.append(getSemester());
		sb.append(", year=");
		sb.append(getYear());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", major=");
		sb.append(getMajor());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.liferay.live.sb.demo.model.Course");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>courseId</column-name><column-value><![CDATA[");
		sb.append(getCourseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>instructorId</column-name><column-value><![CDATA[");
		sb.append(getInstructorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseCatalogId</column-name><column-value><![CDATA[");
		sb.append(getCourseCatalogId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creditHours</column-name><column-value><![CDATA[");
		sb.append(getCreditHours());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>semester</column-name><column-value><![CDATA[");
		sb.append(getSemester());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>major</column-name><column-value><![CDATA[");
		sb.append(getMajor());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Course.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Course.class
		};
	private long _courseId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _instructorId;
	private long _originalInstructorId;
	private boolean _setOriginalInstructorId;
	private long _courseCatalogId;
	private long _originalCourseCatalogId;
	private boolean _setOriginalCourseCatalogId;
	private int _creditHours;
	private int _semester;
	private int _originalSemester;
	private boolean _setOriginalSemester;
	private int _year;
	private int _originalYear;
	private boolean _setOriginalYear;
	private String _name;
	private String _major;
	private long _columnBitmask;
	private Course _escapedModelProxy;
}