/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.live.sb.demo.model.impl;

import com.liferay.live.sb.demo.model.Student;
import com.liferay.live.sb.demo.model.StudentModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Student service. Represents a row in the &quot;SBDemo_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.live.sb.demo.model.StudentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StudentImpl}.
 * </p>
 *
 * @author dnebinger
 * @see StudentImpl
 * @see com.liferay.live.sb.demo.model.Student
 * @see com.liferay.live.sb.demo.model.StudentModel
 * @generated
 */
public class StudentModelImpl extends BaseModelImpl<Student>
	implements StudentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a student model instance should use the {@link com.liferay.live.sb.demo.model.Student} interface instead.
	 */
	public static final String TABLE_NAME = "SBDemo_Student";
	public static final Object[][] TABLE_COLUMNS = {
			{ "studentId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "enrolled", Types.BOOLEAN },
			{ "enrollmentDate", Types.TIMESTAMP },
			{ "yearInSchool", Types.INTEGER },
			{ "major", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SBDemo_Student (studentId LONG not null primary key,userId LONG,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,enrolled BOOLEAN,enrollmentDate DATE null,yearInSchool INTEGER,major VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SBDemo_Student";
	public static final String ORDER_BY_JPQL = " ORDER BY student.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SBDemo_Student.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.live.sb.demo.model.Student"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.live.sb.demo.model.Student"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.live.sb.demo.model.Student"),
			true);
	public static long MAJOR_COLUMN_BITMASK = 1L;
	public static long YEARINSCHOOL_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.live.sb.demo.model.Student"));

	public StudentModelImpl() {
	}

	public long getPrimaryKey() {
		return _studentId;
	}

	public void setPrimaryKey(long primaryKey) {
		setStudentId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_studentId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Student.class;
	}

	public String getModelClassName() {
		return Student.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("studentId", getStudentId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("enrolled", getEnrolled());
		attributes.put("enrollmentDate", getEnrollmentDate());
		attributes.put("yearInSchool", getYearInSchool());
		attributes.put("major", getMajor());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long studentId = (Long)attributes.get("studentId");

		if (studentId != null) {
			setStudentId(studentId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Boolean enrolled = (Boolean)attributes.get("enrolled");

		if (enrolled != null) {
			setEnrolled(enrolled);
		}

		Date enrollmentDate = (Date)attributes.get("enrollmentDate");

		if (enrollmentDate != null) {
			setEnrollmentDate(enrollmentDate);
		}

		Integer yearInSchool = (Integer)attributes.get("yearInSchool");

		if (yearInSchool != null) {
			setYearInSchool(yearInSchool);
		}

		String major = (String)attributes.get("major");

		if (major != null) {
			setMajor(major);
		}
	}

	public long getStudentId() {
		return _studentId;
	}

	public void setStudentId(long studentId) {
		_studentId = studentId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	public boolean getEnrolled() {
		return _enrolled;
	}

	public boolean isEnrolled() {
		return _enrolled;
	}

	public void setEnrolled(boolean enrolled) {
		_enrolled = enrolled;
	}

	public Date getEnrollmentDate() {
		return _enrollmentDate;
	}

	public void setEnrollmentDate(Date enrollmentDate) {
		_enrollmentDate = enrollmentDate;
	}

	public int getYearInSchool() {
		return _yearInSchool;
	}

	public void setYearInSchool(int yearInSchool) {
		_columnBitmask |= YEARINSCHOOL_COLUMN_BITMASK;

		if (!_setOriginalYearInSchool) {
			_setOriginalYearInSchool = true;

			_originalYearInSchool = _yearInSchool;
		}

		_yearInSchool = yearInSchool;
	}

	public int getOriginalYearInSchool() {
		return _originalYearInSchool;
	}

	public String getMajor() {
		if (_major == null) {
			return StringPool.BLANK;
		}
		else {
			return _major;
		}
	}

	public void setMajor(String major) {
		_columnBitmask |= MAJOR_COLUMN_BITMASK;

		if (_originalMajor == null) {
			_originalMajor = _major;
		}

		_major = major;
	}

	public String getOriginalMajor() {
		return GetterUtil.getString(_originalMajor);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Student.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Student toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Student)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		StudentImpl studentImpl = new StudentImpl();

		studentImpl.setStudentId(getStudentId());
		studentImpl.setUserId(getUserId());
		studentImpl.setCreateDate(getCreateDate());
		studentImpl.setModifiedDate(getModifiedDate());
		studentImpl.setName(getName());
		studentImpl.setEnrolled(getEnrolled());
		studentImpl.setEnrollmentDate(getEnrollmentDate());
		studentImpl.setYearInSchool(getYearInSchool());
		studentImpl.setMajor(getMajor());

		studentImpl.resetOriginalValues();

		return studentImpl;
	}

	public int compareTo(Student student) {
		int value = 0;

		value = getName().compareTo(student.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Student student = null;

		try {
			student = (Student)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = student.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		StudentModelImpl studentModelImpl = this;

		studentModelImpl._originalYearInSchool = studentModelImpl._yearInSchool;

		studentModelImpl._setOriginalYearInSchool = false;

		studentModelImpl._originalMajor = studentModelImpl._major;

		studentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Student> toCacheModel() {
		StudentCacheModel studentCacheModel = new StudentCacheModel();

		studentCacheModel.studentId = getStudentId();

		studentCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			studentCacheModel.createDate = createDate.getTime();
		}
		else {
			studentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			studentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			studentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		studentCacheModel.name = getName();

		String name = studentCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			studentCacheModel.name = null;
		}

		studentCacheModel.enrolled = getEnrolled();

		Date enrollmentDate = getEnrollmentDate();

		if (enrollmentDate != null) {
			studentCacheModel.enrollmentDate = enrollmentDate.getTime();
		}
		else {
			studentCacheModel.enrollmentDate = Long.MIN_VALUE;
		}

		studentCacheModel.yearInSchool = getYearInSchool();

		studentCacheModel.major = getMajor();

		String major = studentCacheModel.major;

		if ((major != null) && (major.length() == 0)) {
			studentCacheModel.major = null;
		}

		return studentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{studentId=");
		sb.append(getStudentId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", enrolled=");
		sb.append(getEnrolled());
		sb.append(", enrollmentDate=");
		sb.append(getEnrollmentDate());
		sb.append(", yearInSchool=");
		sb.append(getYearInSchool());
		sb.append(", major=");
		sb.append(getMajor());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.live.sb.demo.model.Student");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>studentId</column-name><column-value><![CDATA[");
		sb.append(getStudentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enrolled</column-name><column-value><![CDATA[");
		sb.append(getEnrolled());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enrollmentDate</column-name><column-value><![CDATA[");
		sb.append(getEnrollmentDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yearInSchool</column-name><column-value><![CDATA[");
		sb.append(getYearInSchool());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>major</column-name><column-value><![CDATA[");
		sb.append(getMajor());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Student.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Student.class
		};
	private long _studentId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _name;
	private boolean _enrolled;
	private Date _enrollmentDate;
	private int _yearInSchool;
	private int _originalYearInSchool;
	private boolean _setOriginalYearInSchool;
	private String _major;
	private String _originalMajor;
	private long _columnBitmask;
	private Student _escapedModelProxy;
}